#!/bin/bash

# Install rust
curl https://sh.rustup.rs -sSf > install_rust.sh
sh install_rust.sh -y
source "$HOME/.cargo/env"

#install risc0
cargo install cargo-binstall
cargo binstall cargo-risczero
cargo risczero install 

# clone risc0
mkdir -p /workspace/Source/GitHub/risc0
git clone https://github.com/risc0/risc0.git /workspace/Source/GitHub/risc0
cd /workspace/Source/GitHub/risc0
git checkout v0.20.1

# clone demo
mkdir -p /workspace/Source/GitHub/simonerom/depin-zk-test
git clone https://github.com/simonerom/depin-zk-test.git /workspace/Source/GitHub/simonerom/depin-zk-test
